# Utilisation de l'image officielle Node.js 
FROM node:14
# Création du répertoire de travail 
WORKDIR /usr/src/app
# Copie des fichiers nécessaires dans le conteneur 
COPY package*.json ./
# Installation des dépendances 
RUN npm install
# Copie du reste des fichiers 
COPY . .
# Commande par défaut pour démarrer l'application 
CMD ["npm", "start"]